language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
    - composer self-update

install:
    - composer --prefer-source install
    - phpunit --coverage-clover=coverage.clover

after_script:
    - wget -N https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover